# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: .
include: ['_pages']


# Site settings
title: LemonPy
email: lemon4py@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Urban vegetation phenology analysis. Sattelite image based, open source and
  community powered
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lemon-py.github.io/" # the base hostname & protocol for your site
twitter_username: Lemon4Py
github_username:  lemon-py

# Build settings
markdown: kramdown
